---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: Read device information of /dev/xvdf
    parted: device=/dev/xvdf unit=MiB
    register: sdb_info
  - name: Create a new primary partition with a size of 2GB
    parted:
      device: /dev/xvdf
      number: "{{ sdb_info.partitions | length + 1 }}"
      state: present
      part_end: 2GiB