---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  - name: Create a new primary partition with a size of 1GiB
    parted:
      device: /dev/xvdf
      number: "{{ sdb_info.partitions | length + 1 }}"
      state: present
      part_end: 2GiB