---
- name: Install Docker
  hosts: all
  become: true

  tasks:
    # Retrieves file systems
  - name: get df list
    shell: "df -hT"
    register: directories
    no_log: true

  # Prints out the file systems
  - name: Display df list
    debug:
      msg: "{{ disks.stdout.split('\n') }}"

  - pause:
      prompt: "What directory do you want to check?"
      echo: yes
    register: result
    
  - set_fact:
      directory: "{{ result.user_input }}"
    no_log: true

  - name: Check if provided directory exists
    stat:
      path: "{{ directory }}"
    register: mainDirectory

  - name: Throw error if provided directory doesn't exist
    fail:
      msg: "{{ directory }} doesn't exist"
    when: not mainDirectory.stat.exists