---
- name: Install Docker
  hosts: all
  become: true

  vars_prompt:
  - name: directory
    prompt: What directory do you want to check?
    private: no

  tasks:
  - name: Check if provided directory exists
    stat:
      path: "{{ directory }}"
    register: mainDirectory

  - name: Throw error if provided directory doesn't exist
    fail:
      msg: "{{ directory }} doesn't exist"
    when: not mainDirectory.stat.exists