---
- name: Handle config files
  hosts: all
  become: true
  vars:
    clone_location: "/tmp/magento"
    repository: "https://github.com/ginokok1996/Technative-DevOps-Scripts.git"
    version: "master"

  tasks:
    # Make sure we have git installed
    - name: Install git
      yum:
        name: 
          - git
        state: latest
    
    # clone the repository
    - name: Cloning the repository
      git:
        repo: "{{ repository }}"
        dest: "{{ clone_location }}"
        version: "{{ version }}"

    # remove the cloned repository
    - name: Removing the repository
      file:
        path: "{{ clone_location }}"
        state: absent
