---
- name: Handle config files
  hosts: all
  become: true
  vars:
    clone_location: "/tmp/magento"
    repository: "https://github.com/ginokok1996/Technative-DevOps-Scripts.git"
    version: "master"
    mount_location: "/tmp/test"
    directories: ['appl', 'apps', 'data', 'config']

  tasks:
    # Make sure we have git installed
    - name: Install git
      yum:
        name: 
          - git
        state: latest
    
    # clone the repository
    - name: Cloning the repository
      git:
        repo: "{{ repository }}"
        dest: "{{ clone_location }}"
        version: "{{ version }}"

    # make sure we have the desired directories in the mount location
    - name: Make sure we have desired directories
      file:
        path: "{{ mount_location }}/{{ item }}"
        state: directory
        mode: "0755"
        with_items: "{{ directories }}"

    # remove the cloned repository
    - name: Removing the repository
      file:
        path: "{{ clone_location }}"
        state: absent
