---
- name: Install composer
  hosts: all
  become: true

  tasks:
    - name: Installing epel-release
      yum:
        name: epel-release
        state: present
    - name: Installing Remi Repository
      yum_repository:
        description: repo for docker
        name: remi
        baseurl: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi2018
        gpgcheck: yes
