---
- name: Create partition
  hosts: all
  become: true

  tasks:
  # Retrieve the device info so we can define the number, part_start & part_end for the partition
  - name: Read device information of /dev/xvdf
    parted: device=/dev/xvdf unit=MiB
    register: device_info
  # Retrieves disk list
  - name: get disk list
    shell: "parted -l"
    register: disks
  # Prints out the available disks
  - name: Display parted list
    debug:
      msg: "{{ disks.stdout.split('\n') }}"
  - pause:
      prompt: "Please enter the device name you wish to use"
      echo: yes
    register: result
  - set_fact:
      device: "{{ result.user_input }}"
  - debug:
      var: device