---
- name: Install Docker
  hosts: all
  become: true

  tasks:
    - pause:
        prompt: "Please provide the directory path you want to mount this partition on (E.g: /mount/xvda)"
        echo: yes
      register: result
    - set_fact:
        directory: "{{ result.user_input }}"
      no_log: true

    - command: "mountpoint {{ directory }}"
      register: mpoint
      failed_when: '"is a mountpoint" in directory'