---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  # Retrieves disk list
  - name: get disk list
    shell: "df -hT"
    register: mountedList
    no_log: true

  # Prints out the available disks
  - name: Display parted list
    debug:
      msg: "{{ mountedList.stdout.split('\n') }}"