---
- name: Testing playbook
  hosts: all
  become: true

  tasks:
    - name: Create a network
      docker_network:
        name: magento

    - name: Create a mailhog container
      docker_container:
        restart_policy: 'always'
        name: mail
        image: 'mailhog/mailhog:latest'
        ports: 
          - '1025:1025'
          - '8025:8025'
        hostname: "mail.magento2.docker"
        networks:
          - name: magento
            aliases:
              - "mail.magento2.docker"