---
- name: Testing playbook
  hosts: all
  become: true

  tasks:
    - name: Create a network
      docker_network:
        name: magento

    - name: Create a elastic search
      docker_container:
        restart_policy: 'always'
        name: elasticsearch
        image: 'magento/magento-cloud-docker-elasticsearch:7.7-1.3.0'
        volumes:
          - './.docker/elasticsearch/data:/usr/share/elasticsearch/data:rw,delegated'
          - './.docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw,delegated'
        ports: 
          - '9200:9200'
          - '9300:9300'
        hostname: "elasticsearch.magento2.docker"
        networks:
          - name: magento
            aliases:
              - "elasticsearch.magento2.docker"