---
- name: Testing playbook
  hosts: all
  become: true

  tasks:
    # create the magento network
    - name: Create magento network network
      docker_network:
        name: magento

    # create the database container
    - name: Create a mariaDB container
      docker_container:
        name: db
        image: 'mariadb:10.3'
        ports: 
          - '3306'
        env:
          MYSQL_ROOT_PASSWORD: "magento2"
          MYSQL_DATABASE: "magento2"
          MYSQL_USER: "magento2"
          MYSQL_PASSWORD: "magento2"
        hostname: "db.magento2.docker"
        volumes:
          - "/mount/main/data/db:/var/lib/mysql"
          - "/mount/main/config/mysql/conf.d:/etc/mysql/conf.d"
        networks:
          - name: magento
            aliases:
              - "db.magento2.docker"