---
- name: Install Docker
  hosts: all
  become: true

  tasks:
  # Retrieves mount list
  - name: get mounted list
    shell: "df -hT"
    register: mountedList
    no_log: true

  # Prints out the currently mounted directories
  - name: Display mounted list
    debug:
      msg: "{{ mountedList.stdout.split('\n') }}"